"""add embedding column to chunk

Revision ID: e8a104fb7ac9
Revises: ec8c4a5f4628
Create Date: 2026-08-30 05:20:16.756888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector

from app.core.config import settings


# revision identifiers, used by Alembic.
revision: str = 'e8a104fb7ac9'
down_revision: Union[str, Sequence[str], None] = 'ec8c4a5f4628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('embedding', Vector(dim=settings.embedding_dimensions), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'embedding')
    # ### end Alembic commands ###
